### ISSUE TITLE
Still working?

### ISSUE THREAD

**Issue by knackko** [GreenMeteor/humhub-discord-module#2]
Hi I've made the configuration to login with discord on humhub website http://www.simagenda.com but got the following message:
"Attribut d'e-mail manquant depuis AuthClient. " : missing e-mail from Authclient

Maybe an update on discord api?

**Comment by ArchBlood** [comment]
This module at this time isn't updated with the latest version of the Discord OAuth provided in [GreenMeteor/humhub-oauth](https://github.com/GreenMeteor/humhub-oauth/tree/master/oauth/Discord)

**Comment by ArchBlood** [comment]
On a side note, I was able to fully login as well as create an account on your site.

**Comment by knackko** [comment]
Hi,
It worked after editing modules/discord/authclient/Discord.php regarding the scope:
public $scope = 'identify email';

It then works globally, but sometimes, it didn't for some clients, I didnt find why at this time.

**Comment by ArchBlood** [comment]
I'll continue to monitor this to see if it happens again, in the meantime, if you get any error stacks please report them here.
